Refactor registry namespace check to be compatible with OSDF topology
PelicanPlatform/pelican pull request #1038
Opened 2024-04-03 18:48 UTC by haoming29

Closes #1029 

The updated policy is as follows (only for OSDF):

Given that a namespace exists in the topology, say `/foo`:
* If an origin server has prefix `/foo` or `/foo/**/**`, and the admin starts the server without registering the namespace at registry website, the auto-registration in the origin will _fail_, with an error message to ask them register the namespace at the registry web UI:
```
The namespace <namespace> already exists in the OSDF topology. "To register a Pelican equivalence, you need to present your identity. If you are registering through Pelican CLI, try again with the flag '--with-identity' enabled. If this is an auto-registration from a Pelican origin or cache server, register your namespace or server through the Pelican registry website at <registry url> instead.
```
* If the admin attempts to register a namespace `/foo` or `/foo/**/**` via Pelican CLI (`pelican namespace register`) but without the `--with-identity` flag, the registration will also _fail_, with the same error message as above
* If the admin register the namespace /foo` or `/foo/**/**` via Pelican CLI  with `--with-identity` flag OR via the registry web UI. The registration will succeed. However, there will be a note in the registration `Description` field as `[ Attention: Prefix exists in OSDF topology ]` to warn the registry admin to pay extra attention when reviewing it.

This PR also removes topology check from `checkNamespaceExists` and function alike to maintain consistency.

This should fix all the incompatibility between Pelican namespace and OSDF legacy namespaces. However, one pitfall is that the director also fetches namespace from both OSDF and Pelican servers, and there can be two situations:
* The Pelican origin server that serves the OSDF namespace prefix has the **exactly same** origin server advertisement as we parsed from the topology. This way, the two server advertisement will race against each other every time we update topology/origin server advertises itself to the director. The consequence is unknown
* The Pelican origin server has different fields in the origin advertisement, and we record both in the director TTL cache. Then we essentially have two servers serving the same namespace, which shouldn't be an issue, just make things a bit intertwined.

2024-04-04 18:44 UTC, haoming29 commented
@jhiemstrawisc this one should be good to go. See PR description for how to test e2e locally.

2024-04-04 21:41 UTC, jhiemstrawisc commented
One comment about the error I get from serving the origin:
```
The namespace /chtc/itb/jhiemstra already exists in the OSDF topology
```
I think this is somewhat misleading, because that full namespace prefix _isn't_ registered in topology. Is there a way to indicate specifically that in order to register a sub namespace of `/chtc/itb` (or maybe it's just `/chtc`, whichever is actually registered) the user has to follow the provided steps?

2024-04-04 21:50 UTC, haoming29 commented
> One comment about the error I get from serving the origin:
> 
> ```
> The namespace /chtc/itb/jhiemstra already exists in the OSDF topology
> ```
> 
> I think this is somewhat misleading, because that full namespace prefix _isn't_ registered in topology. Is there a way to indicate specifically that in order to register a sub namespace of `/chtc/itb` (or maybe it's just `/chtc`, whichever is actually registered) the user has to follow the provided steps?

I agree the wording is kind of misleading, I can work on feeding the exact topology namespace that's taken but I think a quicker fix would be rewording the error message and say "part of the namespace ...." instead? I can do either way.

2024-04-04 22:03 UTC, jhiemstrawisc requested changes
A few cleanup items, but I'm convinced that this should solve our issue by giving federation admins a way to bypass the previous restrictions we had in place.

2024-04-04 22:03 UTC, jhiemstrawisc commented on registry/registry_ui.go
> +			ns.AdminMetadata.Description = "[ Attention: Prefix exists in OSDF topology ] " + ns.AdminMetadata.Description
And here as well -- we should be explicit about whether the namespace exists or whether some super-space of the attempted registration exists

2024-04-04 22:03 UTC, jhiemstrawisc commented on registry/registry_validation.go
> +	// we the flag is on. This is to make sure the topology check is independent
we --> when

2024-04-05 18:38 UTC, jhiemstrawisc approved these changes
LGTM!

2024-04-05 18:38 UTC, jhiemstrawisc commented
@turetske, I believe we need to patch this into 7.6 before EoD

2024-04-05 18:38 UTC, merged