More error tolerant web ui check
PelicanPlatform/pelican pull request #1040
Opened 2024-04-03 19:50 UTC by haoming29

Should fix #1033 

The suspicion is that there's a racing condition at the registry start somehow, and the web engine is not "ready-ready" to serve requests, although it could be other issues. However, this PR will make the web ui check more robust in case of the error code returned

2024-04-03 21:24 UTC, bbockelm requested changes
I don't understand what this code is trying to do.

`WaitUntilWorking` tries a URL every 50ms until it succeeds or 10 seconds has passed.  It seems the code adds another set of loops to retry on top of retries (which appears strange?) ... no?

2024-04-03 21:34 UTC, haoming29 commented
> I don't understand what this code is trying to do.
> 
> `WaitUntilWorking` tries a URL every 50ms until it succeeds or 10 seconds has passed. It seems the code adds another set of loops to retry on top of retries (which appears strange?) ... no?

My guessing of William hitting that 404 error is that the gin server wasn't fully started before we hit the health check endpoint. Since 404 instead of 200 was returned, `WaitUntilWorking` returns immediately and we never get a chance to check it a bit later. I don't want to chance how `WaitUntilWorking` works because in most situations it makes sense to fail immediately if the status code is different from expected, but for the registry's case, it would probably worth waiting and checking again if the status code doesn't match

2024-04-03 21:44 UTC, bbockelm commented
Gotcha.  I would rather add another option to WaitUntilWorking to make the wrong response code non-fatal.  Layers of retries are a bit scary.

2024-04-03 21:46 UTC, haoming29 commented
> Gotcha. I would rather add another option to WaitUntilWorking to make the wrong response code non-fatal. Layers of retries are a bit scary.

Sounds good. I'll refactor the code

2024-04-04 15:55 UTC, jhiemstrawisc commented
@haoming29 is this ready for review or should I wait a bit longer?

2024-04-04 17:48 UTC, haoming29 commented
> @haoming29 is this ready for review or should I wait a bit longer?

Sorry I haven't get the chance to work on the refactoring. I will let you know when its' review for another round of review

2024-04-04 20:47 UTC, haoming29 commented
@jhiemstrawisc Should be good for the review. The Ubuntu test failure should be a random one and re-running it will likely fix the issue

2024-04-05 03:34 UTC, bbockelm approved these changes
LGTM

2024-04-05 13:53 UTC, jhiemstrawisc requested changes
A few small typos, otherwise LGTM

2024-04-05 13:53 UTC, jhiemstrawisc commented on server_utils/server_utils.go
> +							log.Info(statusError, "Will retry until timeedout")
timeedout --> timeout

2024-04-05 13:53 UTC, jhiemstrawisc commented on server_utils/server_utils.go
> +// Pass true to statusMismatch to allow a mismatch of expected status code and what's returned not fail immediatelys
immediatelys --> immediately

2024-04-05 13:53 UTC, jhiemstrawisc commented on server_utils/server_utils.go
> +								log.Info(statusError, "Will retry until timeedout")
Same here

2024-04-05 13:53 UTC, jhiemstrawisc commented on server_utils/server_utils.go
> +								log.Info(statusError, "Will retry until timeedout")
Here too

2024-04-05 16:37 UTC, haoming29 commented
> A few small typos, otherwise LGTM

Thanks for catching them!

2024-04-05 18:56 UTC, jhiemstrawisc approved these changes
LGTM. Thanks!

2024-04-05 18:56 UTC, merged