Standardize API JSON response
PelicanPlatform/pelican pull request #1067
Opened 2024-04-08 15:00 UTC by haoming29

Closes #900

2024-04-16 20:03 UTC, turetske requested changes

2024-04-16 20:03 UTC, turetske commented on registry/registry_ui.go
> +				Msg:    fmt.Sprintf("Invalid query parameters %s: status must be one of  'Pending', 'Approved', 'Denied', 'Unknown'", queryParams.Status)})
```suggestion
				Msg:    fmt.Sprintf("Invalid query parameters %s: status must be one of 'Pending', 'Approved', 'Denied', 'Unknown'", queryParams.Status)})
```

2024-04-17 20:32 UTC, haoming29 commented on director/director_ui.go
> +			Msg:    "name is a required path parameter",
Good point. However this is a special case where `name` refers to the name of the query parameter. I'll add quotes to highlight

2024-04-22 19:51 UTC, turetske approved these changes

2024-04-23 20:42 UTC, merged

2024-04-23 20:44 UTC, haoming29 commented
@CannonLock we might want to update UI for error handling parts to use this new struct, but that would be a separate PR