Made additional retryable errors
PelicanPlatform/pelican pull request #1101
Opened 2024-04-11 15:20 UTC by joereuss12

Made StoppedTransferError and Cannot allocate memory a retryable error

2024-04-11 17:40 UTC, haoming29 approved these changes
LGTM!

2024-04-11 22:38 UTC, bbockelm requested changes
Basic idea is good, just nits about the visibility.  Since we want others to eventually use the client module, we need to be extremely careful about exported types and methods.

2024-04-11 22:38 UTC, bbockelm commented on client/errorAccum.go
> +func (te *TransferErrors) ResetErrors() {
It seems this is only used by unit tests - please change to not be exported outside the module.

2024-04-11 22:38 UTC, bbockelm commented on client/handle_http.go
> +	AllocateMemoryError struct {
It doesn't seem this needs to be visible outside the module - please don't export.

2024-04-13 18:40 UTC, bbockelm approved these changes

2024-04-13 18:40 UTC, merged