Refactor Get/SetPreferredPrefix ConfigPrefix type
PelicanPlatform/pelican pull request #1102
Opened 2024-04-11 16:43 UTC by joereuss12

Refactored the functionality of Get/SetPreferredPrefix to utilize the ConfigPrefix type to further ensure whatever prefixes we get/set are correct.

2024-04-11 22:42 UTC, bbockelm requested changes
One simple change; will cause more code churn but makes for better symmetry.

2024-04-11 22:42 UTC, bbockelm commented on config/config.go
> +func SetPreferredPrefix(newPref string) (oldPref ConfigPrefix, err error) {
Let's have this function take a typed parameter as input, not string.

2024-04-15 14:24 UTC, jhiemstrawisc approved these changes
LGTM

2024-04-15 22:01 UTC, bbockelm approved these changes

2024-04-15 22:02 UTC, merged