NEAREST_CACHE preprend cache list when specified
PelicanPlatform/pelican pull request #1187
Opened 2024-04-29 18:28 UTC by joereuss12

To specify the local cache, users need to set the NEAREST_CACHE env variable. In the old functionality, setting this means we do not look for any other caches and just try to use this "preferred cache". Now, if the specified NEAREST_CACHE has a '+' character at the end of it, it will now append the "normal" list of caches behind the preferred cache in the list of caches to try.

2024-04-29 22:32 UTC, bbockelm commented
@joereuss12 -
- Can you link this to the corresponding issue?  At least from the mobile UI it appears it's not linked.
- I think the original idea was to treat NEAREST_CACHE as a list and to make the + a special list entry.  Can we still do that approach?  That'll allow multiple site-local caches.

2024-04-30 13:55 UTC, joereuss12 commented
> @joereuss12 -
> 
>     * Can you link this to the corresponding issue?  At least from the mobile UI it appears it's not linked.
> 

It says it is linked under development, but here: #1155

2024-04-30 13:56 UTC, joereuss12 commented
>     * I think the original idea was to treat NEAREST_CACHE as a list and to make the + a special list entry.  Can we still do that approach?  That'll allow multiple site-local caches.

Ah, I see what you mean. Yes! I can work that into the implementation!

2024-05-01 20:47 UTC, haoming29 requested changes
One relatively minor change requested otherwise LGTM

2024-05-01 20:47 UTC, haoming29 commented on cmd/object_copy.go
> +		cacheList := strings.Split(preferredCache, ",")
Can we pull this logic into a function? I saw this was repeated a couple of times in different places so I'd be nice if the logic can be shared.

2024-05-01 20:47 UTC, haoming29 commented on cmd/object_get.go
> +		cacheList := strings.Split(preferredCache, ",")
same here

2024-05-01 20:47 UTC, haoming29 commented on cmd/plugin.go
> +	var nearestCacheURL *url.URL
here as well

2024-05-01 20:48 UTC, haoming29 commented
You may also want to merge/rebase against main to let the macOS test pass

2024-05-02 14:40 UTC, haoming29 approved these changes
Revised code LGTM

2024-05-02 21:14 UTC, merged