Report cache hits/misses
PelicanPlatform/pelican pull request #1301
Opened 2024-05-19 08:35 UTC by bbockelm

This PR tracks whether there was a cache hit or miss based on the `Age` header in the server response.  The goal is to provide some indication to users in the hold message as to why their transfer failed -- was it a slow origin or a slow cache?  (The assumption is if it was a cache hit and a slow transfer then the cache is at fault.)

Also in this PR:
- Minor cleanup of the debug log messages when doing transfers.  Less repetition; do not print caches that we won't ever use.
- Fix the pre-transfer queries to selected cache hosts; particularly, put caches that respond with an error to the back of the list.
- Send correct header for PROPFIND request.
- Fix a small "airplane mode" issue causing tests to fail when there's no internet connectivity.

2024-05-21 16:55 UTC, jhiemstrawisc requested changes

2024-05-21 16:55 UTC, jhiemstrawisc commented on client/handle_http.go
>  	// Test the transfer speed every 5 seconds
Can you update this comment

2024-05-21 16:55 UTC, jhiemstrawisc commented on client/handle_http.go
> +	stoppedTransferTimeout := time.Duration(param.Client_StoppedTransferTimeout.GetInt()) * time.Second
Can this be simplified to use param's `GetDuration()`?

2024-05-21 16:55 UTC, jhiemstrawisc commented on client/handle_http_test.go
> +	config.InitConfig()
And here.

2024-05-29 12:37 UTC, bbockelm commented on config/config.go
> -	viper.SetDefault("Client.SlowTransferWindow", 30)
The code above breaks in a different direction: these parameters need to be set for the local cache (which calls `InitServer`) but only have defaults in `InitClient`.

By moving this to `defaults.yaml`, it's available to both client and server.

The problem Ismael was hitting is he didn't invoke `InitClient` at all -- I believe the best approach there is to have the client API throw an error when it's used without `InitClient()` being called.

2024-06-04 13:52 UTC, jhiemstrawisc approved these changes
LGTM

2024-06-04 13:53 UTC, merged