Updated mpb bar progress bars
PelicanPlatform/pelican pull request #132
Opened 2023-09-13 20:24 UTC by joereuss12

This fixes a bug when downloading from an origin for the first time and a weird error message shows up. Turns out the package needed some updating. This took some time since the function we originally had for v7 no longer existed in v8. Also changed around the styling a tad and made it look nice and work with this new version upgrade. Removed what I thought was an unnecessary extra bar being made to say "done". Also found a typo to be fixed within handle_http.

2023-09-13 21:48 UTC, jhiemstrawisc commented
Hey @joereuss12, it looks like something that was changed is causing the Test action to throw this:
```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x8115ec]
```

Can you investigate and let me know when you've patched things back up?

2023-09-14 16:00 UTC, joereuss12 commented
@jhiemstrawisc just updated with some more changes too. I can undo the log level if needed depending on how Brian responds to the issue I made (#135) and I'll make a note in the issue to revert it back if needed.

2023-09-16 14:34 UTC, bbockelm requested changes
The big item to focus on is how the `EwmaIncrement` method should be invoked.  It certainly looks wrong right now, always being called with 0.

The other items are mostly minor.

How do we test this functionality?

2023-09-16 14:34 UTC, bbockelm commented on handle_http.go
> +					//cancelledProgressBar.SetTotal(resp.Size, true)
Isn't there a higher function that emits an error message?  Seems strange to do that from the progress bar.

2023-09-18 14:54 UTC, joereuss12 commented on handle_http.go
> +					//log.Warnln("Download speed of ", resp.BytesPerSecond(), "bytes/s", " is below the limit of", downloadLimit, "bytes/s")
I'm not super sure how that ended up commented out. Fixing now, sorry!

2023-09-28 13:32 UTC, merged