Add configuration download
PelicanPlatform/pelican pull request #1348
Opened 2024-05-29 16:40 UTC by CannonLock

- Add extensible button

2024-05-29 16:45 UTC, CannonLock commented
```
Cache:
  Concurrency: 0
  DataLocation: /run/pelican/cache
  DataLocations:
    - /run/pelican/cache/data
  EnableLotman: false
  EnableOIDC: false
  EnableVoms: false
  ExportLocation: /
  HighWaterMark: '95'
  LocalRoot: /run/pelican/cache
  LowWatermark: '90'
  MetaLocations:
    - /run/pelican/cache/meta
  PermittedNamespaces: null
  Port: 8442
  RunLocation: /run/pelican/xrootd/cache
  SelfTest: true
  SelfTestInterval: 15000000000
  SentinelLocation: ''
  Url: https://cf52ea2946fa:8442
  XRootDPrefix: ''
Client:
  DisableHttpProxy: false
  DisableProxyFallback: false
  MaximumDownloadSpeed: 0
  MinimumDownloadSpeed: 0
  SlowTransferRampupTime: 0
  SlowTransferWindow: 0
  StoppedTransferTimeout: 0
  WorkerCount: 0
ConfigDir: /etc/pelican
Debug: false
Director:
  AdvertisementTTL: 900000000000
  CacheResponseHostnames: null
  CacheSortMethod: distance
  DefaultResponse: cache
  EnableBroker: true
  EnableOIDC: false
  FilteredServers: null
  GeoIPLocation: /var/cache/pelican/maxmind/GeoLite2-City.mmdb
  MaxMindKeyFile: ''
  MaxStatResponse: 1
  MinStatResponse: 1
  OriginCacheHealthTestInterval: 15000000000
  OriginResponseHostnames: null
  StatConcurrencyLimit: 1000
  StatTimeout: 200000000
  SupportContactEmail: ''
  SupportContactUrl: ''
DisableHttpProxy: false
DisableProxyFallback: false
Federation:
  BrokerUrl: ''
  DirectorUrl: https://cf52ea2946fa:8444
  DiscoveryUrl: ''
  JwkUrl: ''
  RegistryUrl: https://cf52ea2946fa:8444
  TopologyNamespaceUrl: ''
  TopologyReloadInterval: 0
  TopologyUrl: ''
GeoIPOverrides: null
Issuer:
  AuthenticationSource: OIDC
  AuthorizationTemplates: null
  GroupFile: ''
  GroupRequirements: null
  GroupSource: ''
  IssuerClaimValue: ''
  OIDCAuthenticationRequirements: null
  OIDCAuthenticationUserClaim: sub
  OIDCGroupClaim: groups
  QDLLocation: /opt/qdl
  ScitokensServerLocation: /opt/scitokens-server
  TomcatLocation: /opt/tomcat
  UserStripDomain: false
IssuerKey: /etc/pelican/issuer.jwk
LocalCache:
  DataLocation: /run/pelican/localcache/cache
  HighWaterMarkPercentage: 95
  LowWaterMarkPercentage: 85
  RunLocation: /run/pelican/localcache
  Size: ''
  Socket: /run/pelican/localcache/cache.sock
Logging:
  Cache:
    Http: error
    Ofs: error
    Pfc: info
    Pss: error
    Scitokens: fatal
    Xrd: error
    Xrootd: error
  DisableProgressBars: false
  Level: Error
  LogLocation: ''
  Origin:
    Cms: error
    Http: error
    Ofs: error
    Oss: error
    Scitokens: fatal
    Xrd: error
    Xrootd: info
Lotman:
  DbLocation: /var/lib/pelican
  EnableAPI: false
  LibLocation: ''
  Lots: null
MinimumDownloadSpeed: 0
Monitoring:
  AggregatePrefixes:
    - /*
  DataLocation: /var/lib/pelican/monitoring/data
  MetricAuthorization: true
  PortHigher: 9999
  PortLower: 9930
  PromQLAuthorization: true
  TokenExpiresIn: 3600000000000
  TokenRefreshInterval: 300000000000
OIDC:
  AuthorizationEndpoint: https://cilogon.org/authorize
  ClientID: ''
  ClientIDFile: /etc/pelican/oidc-client-id
  ClientRedirectHostname: ''
  ClientSecretFile: /etc/pelican/oidc-client-secret
  DeviceAuthEndpoint: https://cilogon.org/oauth2/device_authorization
  Issuer: https://cilogon.org
  TokenEndpoint: https://cilogon.org/oauth2/token
  UserInfoEndpoint: https://cilogon.org/oauth2/userinfo
Origin:
  EnableBroker: false
  EnableCmsd: false
  EnableDirListing: false
  EnableDirectReads: false
  EnableFallbackRead: false
  EnableIssuer: false
  EnableListings: true
  EnableOIDC: false
  EnablePublicReads: true
  EnableReads: true
  EnableUI: true
  EnableVoms: true
  EnableWrite: false
  EnableWrites: true
  ExportVolume: ''
  ExportVolumes: []
  Exports:
    - capabilities:
        - PublicReads
        - Writes
        - Listings
      federationprefix: /barten
      storageprefix: /mnt/foo
  FederationPrefix: /barten
  HttpServiceUrl: ''
  Mode: ''
  Multiuser: false
  NamespacePrefix: ''
  Port: 8443
  RunLocation: /run/pelican/xrootd/origin
  S3AccessKeyfile: ''
  S3Bucket: ''
  S3Region: ''
  S3SecretKeyfile: ''
  S3ServiceName: ''
  S3ServiceUrl: ''
  S3UrlStyle: path
  ScitokensDefaultUser: ''
  ScitokensMapSubject: false
  ScitokensNameMapFile: ''
  ScitokensRestrictedPaths: null
  ScitokensUsernameClaim: ''
  SelfTest: true
  SelfTestInterval: 15000000000
  StoragePrefix: /mnt/foo
  StorageType: posix
  Url: https://cf52ea2946fa:8443
  XRootDPrefix: ''
  XRootServiceUrl: ''
Plugin:
  Token: ''
Registry:
  AdminUsers: null
  CustomRegistrationFields: null
  DbLocation: /var/lib/pelican/registry.sqlite
  Institutions: null
  InstitutionsUrl: https://topology-institutions.osg-htc.org/api/institution_ids
  InstitutionsUrlReloadMinutes: 900000000000
  RequireCacheApproval: false
  RequireKeyChaining: true
  RequireOriginApproval: false
Server:
  EnableUI: true
  ExternalWebUrl: https://cf52ea2946fa:8444
  Hostname: cf52ea2946fa
  IssuerHostname: ''
  IssuerJwks: ''
  IssuerPort: 0
  IssuerUrl: ''
  Modules:
    - director
    - registry
    - origin
    - cache
  RegistrationRetryInterval: 10000000000
  SessionSecretFile: /etc/pelican/session-secret
  TLSCACertificateDirectory: ''
  TLSCACertificateFile: /etc/pelican/certificates/tlsca.pem
  TLSCAKey: /etc/pelican/certificates/tlsca.key
  TLSCertificate: /etc/pelican/certificates/tls.crt
  TLSKey: /etc/pelican/certificates/tls.key
  UIActivationCodeFile: /etc/pelican/server-web-activation-code
  UIAdminUsers: null
  UILoginRateLimit: 1
  UIPasswordFile: /etc/pelican/server-web-passwd
  WebConfigFile: /etc/pelican/web-config.yaml
  WebHost: 0.0.0.0
  WebPort: 8444
Shoveler:
  AMQPExchange: shoveled-xrd
  AMQPTokenLocation: /etc/pelican/shoveler-token
  Enable: false
  IPMapping: null
  MessageQueueProtocol: amqp
  OutputDestinations: null
  PortHigher: 9999
  PortLower: 9930
  QueueDirectory: /var/spool/pelican/shoveler/queue
  StompCert: ''
  StompCertKey: ''
  StompPassword: ''
  StompUsername: ''
  Topic: ''
  URL: ''
  VerifyHeader: false
StagePlugin:
  Hook: false
  MountPrefix: ''
  OriginPrefix: ''
  ShadowOriginPrefix: ''
TLSSkipVerify: true
Transport:
  DialerKeepAlive: 30000000000
  DialerTimeout: 10000000000
  ExpectContinueTimeout: 1000000000
  IdleConnTimeout: 90000000000
  MaxIdleConns: 30
  ResponseHeaderTimeout: 10000000000
  TLSHandshakeTimeout: 15000000000
Xrootd:
  Authfile: /etc/pelican/xrootd/authfile
  ConfigFile: ''
  DetailedMonitoringHost: ''
  LocalMonitoringHost: ''
  MacaroonsKeyFile: /etc/pelican/macaroons-secret
  ManagerHost: ''
  Mount: /run/pelican/xrootd/cache/export
  Port: 0
  RobotsTxtFile: /run/pelican/xrootd/origin/robots.txt
  RunLocation: ''
  ScitokensConfig: /etc/pelican/xrootd/scitokens.cfg
  Sitename: cf52ea2946fa
  SummaryMonitoringHost: ''
```

2024-05-29 17:42 UTC, CannonLock commented
Closes #1037

2024-05-31 21:53 UTC, haoming29 requested changes
One nitpick for the generate config file is that can we remove entries from the download file if the value is `null`? I don' see a reason why people want to have `null` value in the config and this might cause error if they pass the file as the pelican config. Unfortunately we can't do this for the rest of the configs as there's no "null" thing in most of the Go values.

2024-05-31 21:53 UTC, haoming29 commented on web_ui/frontend/app/config/page.tsx
Any reason we want to move `Config()` to the front and leave all definition/help functions behind? (webpack seems to resort and handle dependencies anyway but just curious)

2024-06-03 18:17 UTC, CannonLock commented on web_ui/frontend/app/config/page.tsx
Yeah I am trying to be better about organizing things correctly. All of these pages really should have the functions organized by precedence so the most important parts are at the top. 90% of the time that these files are edited, or looked at it will be the main component.

2024-06-10 18:46 UTC, haoming29 approved these changes
LGTM!

2024-06-13 17:51 UTC, CannonLock commented
@haoming29 Can I merge, I imagine this is unrelated

2024-06-13 19:57 UTC, merged