Plugin fix wrong start time -  New PR
PelicanPlatform/pelican pull request #1403
Opened 2024-06-11 16:04 UTC by haoming29

This is the new PR for #1331 Refer to the original PR for code review comments that are addressed in this PR.

2024-06-11 16:06 UTC, haoming29 commented
@bbockelm One question about architectural/design thinking. This implementation records the transfer start time as the time at the start of the last attempt. Why don't we record the time at the start of the first attempt?

2024-06-11 17:19 UTC, jhiemstrawisc requested changes

2024-06-11 17:19 UTC, jhiemstrawisc commented on cmd/plugin_test.go
> +	require.NoError(t, err)
Brian recently added `test_utils.InitClient` that handles most of this preamble. Can we modify the test to use that?

2024-06-12 14:28 UTC, jhiemstrawisc approved these changes
👍

2024-06-12 14:28 UTC, merged