Add OSDF Institution Count Metric Collection
PelicanPlatform/pelican pull request #1430
Opened 2024-06-18 16:15 UTC by patrickbrophy

This PR implements a metric for tracking the number of participating institutions in OSDF mode. It includes:
- A goroutine that periodically collects and updates the institution count metric.
- Support for fetching institutions from both configuration values and a URL.
- Integration with Prometheus to expose the metric as `pelican_osdf_institution_count`.

This PR addresses the issue #1424

2024-06-20 21:01 UTC, haoming29 requested changes

2024-06-20 21:01 UTC, haoming29 commented on registry/registry_api.go
> +					log.Warning("Failed to unmarshal institutions.", err.Error())
```suggestion
					log.Warning("Failed to update institution count metric: failed to unmarshal institutions.", err.Error())
```

2024-06-21 16:11 UTC, patrickbrophy reviewed
Implemented all comments from review

2024-06-24 20:34 UTC, haoming29 approved these changes
LGTM!

2024-06-24 20:34 UTC, merged

2024-06-27 16:34 UTC, haoming29 commented
@patrickbrophy can you please link the issue this PR can close? so that we can keep track of the development metrics