Add IP address (host) label to XRootD access metrics
PelicanPlatform/pelican pull request #1445
Opened 2024-06-21 19:09 UTC by patrickbrophy

This PR addresses #1425. This PR adds a IP address (host) label to XRD access metrics (xrootd_transfer_readv_segments_count, xrootd_transfer_operations_count, and xrootd_transfer_bytes). This PR also updated some tests to handle the new label.

2024-06-22 12:22 UTC, bbockelm requested changes
Three requests:
- can we leave out the unrelated movement of structs to a separate module?  That causes code churn unrelated to the PR (but may be fine for a separate PR).
- there's a Xrootd setting, `xrd.network nodnr`, that should disable the use of reverse DNS to create a hostname in the monitoring records.  Can we try setting that here?  See https://xrootd.slac.stanford.edu/doc/dev56/xrd_config.htm#_Toc152596878
- given we are using networks and not hostnames, let's rename the labels to "network" perhaps?  Looking around on Google, it's not clear if there's a standard practice here.

2024-06-22 12:22 UTC, bbockelm commented on utils/utils.go
> +		// Invalid IP
Does this cause an explosion in cardinality if a serves is using hostnames and not an IP?

Good habits would have an indication to the caller that a special case occurred. Maybe also return a Boolean?

2024-06-22 12:22 UTC, bbockelm commented on utils/utils.go
> +		return IPv4Mask(ipStr)
Can we avoid parsing the IP string twice?

2024-06-24 15:09 UTC, patrickbrophy commented
I'm closing this PR to separate out concerns. I'll open a PR for this metric and a separate one for moving around the structs from the utils folder.

2024-06-24 15:09 UTC, closed without merging