Retry auth endpoint if the `stat` timeout
PelicanPlatform/pelican pull request #1465
Opened 2024-06-27 21:55 UTC by haoming29

Fixes #1464 

For topology legacy origins, they have `authUrl` for protected objects and `url` for public objects. However, our `stat` call only checks against `url` as the base url of the object. This PR added an additional attempt to try the `authUrl` endpoint if we get error from the first two attempts (first one is `url` endpoint with digest requested, second one is to get rid of digest)

2024-06-27 21:56 UTC, haoming29 commented
@jhiemstrawisc We should backport this to 7.9 once it's merged. Sorry for all the hassles related to this `stat` feature!

2024-07-01 14:28 UTC, jhiemstrawisc requested changes

2024-07-01 15:08 UTC, haoming29 commented on director/stat.go
> +				if err != nil && baseUrl != sAD.AuthURL && sAD.AuthURL.String() != "" && !errors.As(err, &cancelErr) {
Sure, I can take this route instead, and it can reduce one additional request which is nice to our origin/cache servers

2024-07-01 20:59 UTC, jhiemstrawisc approved these changes
LGTM

2024-07-01 20:59 UTC, merged