Fix various issues in `stat`
PelicanPlatform/pelican pull request #1477
Opened 2024-07-11 17:05 UTC by haoming29

Fixes #1474

2024-07-12 14:41 UTC, jhiemstrawisc requested changes

2024-07-12 14:41 UTC, jhiemstrawisc commented on director/stat_test.go
> +			URL:          url.URL{Host: "mock-private-topo-origin.com", Scheme: "https"},
This is probably a minor-enough detail that it shouldn't effect anything, but the `URL` field from Topology is always `http`, while the `AuthURL` field should always be `https`.

2024-07-12 16:31 UTC, haoming29 commented
@jhiemstrawisc  Things get a little tricker as I made too much changes around the director logic. For this PR, we want to release it as a patch fix to `7.9`, so I'll merge this in first, and I hope there's minimum merge conflicts

However, the issue fixed in this PR are not in #1308 and #1457, and #1308 is merged. So I'll address the issue in #1308 before I hit the merge button AND have a separate PR to fix the issue in #1457 (which does not need to go into 7.9 as we don't support `stat` for caches in 7.9)

Hopefully this all make sense and let me know if there's any questions!

2024-07-30 14:09 UTC, haoming29 commented
@jhiemstrawisc This PR is good for another round of review and should be merged in first than the rest of my pending PRs. I've attached a brief description of the dependencies between my PRs and hopefully that makes sense.

2024-07-30 16:32 UTC, jhiemstrawisc approved these changes
The logic is tricky, but we're gradually finding/fixing the edge cases w.r.t. topology integration. LGTM!

2024-07-30 16:32 UTC, merged