Add "sync" functionality to the client
PelicanPlatform/pelican pull request #1586
Opened 2024-09-07 16:56 UTC by bbockelm

This adds a "rsync-like" interface, `object sync`, to the command line client.  Example:

```
pelican object sync pelican://localhost:8444/tmp/test /tmp/download
```

This can be called multiple times; partially-downloaded files will be completed and completed files will be skipped (similar behavior on uploads).

The intent for this functionality is to allow someone to do a transfer of a large number of files into the OSDF from a host that might be rebooted or otherwise interrupted.

This includes multiple small bugfixes discovered in the client while testing, including:
- Fixed client hang for transfers of empty directories.
- Fixed client hang if the transfers finish before the directory walk finishes
- Do not consider a zero-sized file an error.
- If the director notices a namespace requires authorization -- but the client didn't provide a token -- then don't bother performing a stat (as it's just going to fail immediately).  In this case, the client will retry the director lookup once it's acquired a token.

2024-09-13 19:33 UTC, turetske requested changes
@bbockelm Should this also work on a single large file rather than just a folder? Because currently it only works for folders and trying to do it on a single file fails poorly (tries to PROPFIND a folder with the file name which then fails). If it's the former, then that needs to be fixed. If it's the latter, then it should fail more gracefully. Maybe with something that says "source needs to be a folder"

2024-09-16 14:37 UTC, bbockelm commented
Good catch!  Indeed, it should to the correct thing when you pass it a file name.

That said, what's the current behavior without the patch?  If the "sync" behavior matches the current behavior, I'd consider the behavior a bug and can be fixed in a separate PR.

2024-09-16 16:45 UTC, turetske commented
@bbockelm What do you mean by current behavior? A `pelican object get` of a single file works fine.

2024-09-17 13:55 UTC, turetske approved these changes

2024-09-18 22:30 UTC, bbockelm commented
@turetske - can you redo that last commit with proper git author metadata?  GitHub renders the author as "your name" now.

2024-09-19 13:52 UTC, turetske commented
> @turetske - can you redo that last commit with proper git author metadata? GitHub renders the author as "your name" now.

@bbockelm Done

2024-09-19 15:00 UTC, merged