Origin startup stdout cleanup - Incorporating Goose and build info output into the logging system
PelicanPlatform/pelican pull request #1625
Opened 2024-10-08 20:39 UTC by Saartank

This PR fixes issue #1502 

- It incorporates Goose output into the logging system. Goose has two levels of output: `info` and `fatal`, which are now mapped to the corresponding levels in `logrus`.
- The build information at server startup is now logged as part of the `debug` logs.

2024-10-08 21:06 UTC, bbockelm requested changes
Just one small comment, then I think we're ready to go.

2024-10-08 21:06 UTC, bbockelm commented on config/config.go
> +	log.Debugf("Version: %s", GetVersion())
If all we're doing is concatenating strings together, the `Debugln` variant is more elegant.  Additionally given the information used to be printed all the time by default; let's move it to `Info`:

```suggestion
	log.Infoln("Version:", GetVersion())
```

(and the subsequent lines as well.)

2024-10-09 00:01 UTC, bbockelm commented
@Saartank - looks like there's still a CI failure; can you investigate?

Also, once done, the commit history is a bit scattered on this one.  Please squash it to one commit per piece of functionality.

2024-10-09 22:58 UTC, Saartank commented
Closing this PR because I made a mistake while changing the commit history. Created a new PR with a clean commit history: [https://github.com/PelicanPlatform/pelican/pull/1639](https://github.com/PelicanPlatform/pelican/pull/1639).

2024-10-09 22:58 UTC, closed without merging