Made the xrootd cache prefetch variable configurable via a pelican va…
PelicanPlatform/pelican pull request #1654
Opened 2024-10-14 20:40 UTC by turetske

…riable.

Added the Pelican variabled Cache.Prefix and used it to set the cache prefix value in the cache Changed its default from 20 to 0
Updated the xrootd config and cache templates accordingly

2024-10-17 19:48 UTC, jhiemstrawisc commented
> …riable.
> 
> Added the Pelican variabled Cache.Prefix and used it to set the cache prefix value in the cache Changed its default from 20 to 0 Updated the xrootd config and cache templates accordingly

Just clarifying before I review, is this supposed to be `Cache.Prefix` like the description claims or `Cache.Prefetch` like the title claims?

2024-10-18 19:59 UTC, turetske commented
> > …riable.
> > Added the Pelican variabled Cache.Prefix and used it to set the cache prefix value in the cache Changed its default from 20 to 0 Updated the xrootd config and cache templates accordingly
> 
> Just clarifying before I review, is this supposed to be `Cache.Prefix` like the description claims or `Cache.Prefetch` like the title claims?

Prefetch, I had just been dealing with a lot of Prefix stuff and the typo just came out.

I recommend waiting until I can fix the test failures, though.

2024-10-21 15:51 UTC, jhiemstrawisc requested changes

2024-11-06 20:32 UTC, turetske commented on xrootd/xrootd_config.go
> +		Prefetch       int
This arose from when the S3 origins were being pummeled by the cache. One thing we realized is that we didn't want to prefetch blocks when just doing a stat request.

2024-11-11 19:16 UTC, jhiemstrawisc approved these changes
LGTM. I'll approve pending the failing ubuntu tests (not sure if this is a known flaky test or not).

2024-11-12 14:30 UTC, merged