Docs Overhaul
PelicanPlatform/pelican pull request #1849
Opened 2024-12-20 22:57 UTC by jhiemstrawisc

2025-01-07 17:25 UTC, jhiemstrawisc commented
The three primary things I'm hoping the reviewer will look for are:
1. Language -- I did a lot of jumping around during the multi-week push to add new content, and while I tried to do a final read through of everything, it's likely I trailed off in a few sections that I intended to return to.
2. Verbosity -- As a developer, it's challenging to strike the right balance between all the things I know how to do and not scaring off new people with complicated stuff. I was shooting for lengthier descriptions at the expense of verbosity, but if I got too windy I'm happy to trim anything you see fit.
3. Organization -- wearing your user hat, do you think you could find the right documentation to answer any questions you might have?

2025-01-07 17:32 UTC, jhiemstrawisc commented
Another higher level reorganization I was shooting for was to have each drop-down section of the index have its own landing page. That is, when you click something like "Getting Started", you're brought to a page for that section, which has descriptions of the other sub sections you can click through like "Accessing Data". My goal was to guide users through the maze by giving them more and more granular choices of documentation to read, without making that nesting _too_ deep.

Another screen recording with very slow click times...

https://github.com/user-attachments/assets/ac20862e-4d3f-43cc-a732-5ae7f3b9f176

2025-01-07 17:37 UTC, jhiemstrawisc commented
Finally, if anyone _does_ want to render all this into a locally-hosted website, I followed the instructions provided by Cannon:
https://github.com/PelicanPlatform/docs

2025-01-10 20:48 UTC, aowen-uwmad commented
@jhiemstrawisc can you clarify what you mean by 

> change our landing page so that people are auto-redirected to `About Pelican`

Specifically, where is it redirecting *from* and what was the previous behavior? 
Currently https://docs.pelicanplatform.org/ takes you to the `About Pelican` page..

(I'm starting to review things btw)

2025-01-10 20:59 UTC, jhiemstrawisc commented
> @jhiemstrawisc can you clarify what you mean by
> 
> > change our landing page so that people are auto-redirected to `About Pelican`
> 
> Specifically, where is it redirecting _from_ and what was the previous behavior? Currently https://docs.pelicanplatform.org/ takes you to the `About Pelican` page..
> 
> (I'm starting to review things btw)

This change is mostly transparent for the users, but here's what's happening:

When you visit `https://docs.pelicanplatform.org` with no path, you're actually visiting `https://docs.pelicanplatform.org/index`, which is the conventional landing page for most websites. Right now that "index" page contains the "About Pelican" documentation.

In this PR I wanted to make the "About Pelican" tab in the left index a drop down where clicking on "About Pelican" brings you to content on the current home page, but also displays other "Core Concepts and Terminology" sub section (see the first video for what this will look like). To accomplish that expandable drop down behavior, I had to move the "About Pelican" content to a different place, which means it's no longer the "index" home page. However, I still want that to be what the user sees when they visit `https://docs.pelicanplatform.org`. My fix was to make it so that visiting the index page at `https://docs.pelicanplatform.org` automatically loads `https://docs.pelicanplatform.org/about-pelican` instead.

2025-01-10 21:01 UTC, jhiemstrawisc commented
Maybe the key distinction here is that there is no `https://docs.pelicanplatform.org/about-pelican` in the current docs page, even though we have "About Pelican" docs.

This moves the "About Pelicans" docs to that `/about-pelican` path, which means I had to change the path for the default landing page as well.

2025-01-10 21:03 UTC, aowen-uwmad commented
Ah, I see what you are saying now.

![image](https://github.com/user-attachments/assets/c7ceea4a-3ac6-46dc-ac90-bcbaff27ede7)

That part should be fine then.

2025-01-11 00:38 UTC, aowen-uwmad requested changes
I think we should discuss the main "getting started" page to make sure that we're both on the same page about it (no pun intended).

Other comments, suggestions can be integrated at your discretion.

2025-01-11 00:38 UTC, aowen-uwmad commented on docs/pages/getting-started.mdx
> +
```suggestion
Pelican federations are built from the ground up to take advantage of distributed object caching.
Pelican Caches enable a federation to distribute data - especially frequently reused data - even more efficiently.

That means that even if you don't have data to share in a federation, you can help a federation run more efficiently by serving a cache that utilizes your existing storage resources.

If you are interested in contributing a cache to an existing federation, see [Operating a Federation/Cache](./operating-a-federation/cache.mdx) for the general process.

### Sharing your storage resources with the OSDF

Have storage but don't know any federations to share it with? 

Consider contributing to the Pelican flagship [Open Science Data Federation (OSDF)](https://osdf.osg-htc.org/).
This well-established federation is used to distribute data within the [OSPool](https://osg-htc.org/services/open_science_pool.html), a national distributed computing system that is accessible to any researcher affiliated with a US academic institution. 
The OSDF is connected directly with network backbones like ESNet and Internet2, enabling researchers across the country to incorporate their data in their OSPool workloads.

> NOTE! If you or your campus have a storage allocation granted through something like the NSF's [CC*](https://new.nsf.gov/funding/opportunities/cc-campus-cyberinfrastructure) program, contributing storage to the OSDF can help satisfy some grant requirements.
```

2025-01-11 00:38 UTC, aowen-uwmad commented on docs/pages/getting-started.mdx
> +titled [Registry](./operating-a-federation/registry.mdx).
```suggestion
## Starting Your Own Federation

The Pelican flagship [Open Science Data Federation (OSDF)](https://osdf.osg-htc.org/) is a highly-performant, well-established federation connected directly with network backbones like ESNet and Internet2. 
But if the OSDF does not do not meet the requirements for your data distribution needs, you can still leverage the power of Pelican by launching and maintaining your own Pelican federation.

The process of running/managing a Pelican object federation involves setting up two primary services: a Registry and a Director.
These services are called the federation's "Central Services", where the Registry handles the registration/verification of Caches and Origins and the Director keeps an up-to-date list of where to send clients that want to interact with objects in the federation.

You can find more information about operating these services in the [Operating a Federation](./operating-a-federation.mdx) section. Information specific to
Directors can be found in the sub page titled [Director](./operating-a-federation/director.mdx) while information for Registries can be found in the sub page
titled [Registry](./operating-a-federation/registry.mdx).

```

2025-01-11 00:38 UTC, aowen-uwmad commented on docs/pages/getting-started.mdx
Let me know if you want to discuss my rewrites here.

2025-01-11 00:38 UTC, aowen-uwmad commented on docs/pages/index.mdx
I assume you know what you are doing with this file.

2025-01-11 00:38 UTC, aowen-uwmad commented on docs/public/aggregated-objects.png
I like `"Pelicanized"`. Might have to add that to other places in the docs, tutorials.

2025-01-11 00:38 UTC, aowen-uwmad commented on docs/pages/federating-your-data/choosing-namespaces.mdx
> +registered, then the origin exporting `/project-xyz/jhonson-lab` will not be able to export objects that begin with `foo/`.
Presumed typo.

```suggestion
registered, then the origin exporting `/project-xyz/johnson-lab` will not be able to export objects that begin with `foo/`.
```

2025-01-11 00:38 UTC, aowen-uwmad commented on docs/pages/federating-your-data/choosing-namespaces.mdx
> +other stores its images in posix. Namespacing allows the data owner to elide this fact from data consumers by exporting both the S3 bucket and the posix filesystem under the same
Nice use of `elide`, but if I have to look a word up, 90% of people will need to as well..

```suggestion
other stores its images in posix. Namespacing allows the data owner to hide this fact from data consumers by exporting both the S3 bucket and the posix filesystem under the same
```

2025-01-11 00:38 UTC, aowen-uwmad commented on docs/pages/federating-your-data/choosing-namespaces.mdx
I think this page will be really helpful for folks.

2025-01-14 16:45 UTC, jhiemstrawisc commented on docs/pages/faq.mdx
> +```
I think it was rendering as written before, but I made a quick correction on the line breaks. This is what it'll be in the next version:
![Screenshot 2025-01-14 at 10 44 21](https://github.com/user-attachments/assets/a757dc63-30f6-4dfb-80bd-de08520ec66b)

2025-01-14 16:47 UTC, jhiemstrawisc commented on docs/pages/faq.mdx
Nextra creates a sub-page index on the right hand side. See the "On This Page" piece of this screenshot. I don't love way it looks by default, but I'd like to avoid cosmetic touchup for that in this PR.

![Screenshot 2025-01-14 at 10 45 38](https://github.com/user-attachments/assets/f53286f7-00ed-45bd-8fd1-142fad979196)

2025-01-14 16:55 UTC, jhiemstrawisc commented on docs/pages/federating-your-data.mdx
> +may also be striped across multiple Origins.
After a quick browse-around of alternative docs, I actually think the wikipedia article is the best, since most other things specifically mention RAID.

2025-01-14 17:12 UTC, jhiemstrawisc commented on docs/pages/federating-your-data/choosing-namespaces.mdx
> +other stores its images in posix. Namespacing allows the data owner to elide this fact from data consumers by exporting both the S3 bucket and the posix filesystem under the same
I see where you stand in the "Faulkner v Hemingway" debate 😉 I'll make the change haha

2025-01-14 17:31 UTC, jhiemstrawisc commented on docs/pages/faq.mdx
> +Pelican is built on HTTP, so any client that speaks HTTP can determine this. These instructions are for using `curl` on the command line. Broadly speaking, they require:
I opted for the first suggestion of linking the sections. I think the latter suggestions are additional FAQs that we can add later now that the FAQ scaffolding is here.

2025-01-15 20:40 UTC, jhiemstrawisc commented
The latest series of commits should address all of the review comments. I'm including a screen recording of the new "Getting Started" page so you can see how that renders, since that was the page with the most change requests.

https://github.com/user-attachments/assets/d76a264c-3369-4650-9836-1723e197476e

2025-01-15 22:27 UTC, aowen-uwmad approved these changes
Small suggestion, otherwise LGTM

2025-01-15 22:27 UTC, aowen-uwmad commented on docs/pages/getting-started.mdx
> +**a)** Serving a Cache, or<br />
```suggestion
**a)** Serving a Cache ([see below](#serving-a-cache)), or<br />
```

2025-01-15 22:30 UTC, merged