Add first draft of client usage docs
PelicanPlatform/pelican pull request #249
Opened 2023-10-19 16:34 UTC by jhiemstrawisc

2023-10-19 20:54 UTC, joereuss12 commented
It looks very good to me, detailed with many examples. All good from my side but we can see what Emma thinks too before we merge.

2023-10-20 20:31 UTC, turetske commented
I highly recommend checking your final version via Cannon's docs repository if you have not already done so as I found a few syntax bugs in my own that prevented the page from being rendered when I did.

2023-10-20 20:35 UTC, turetske requested changes
LGTM with minor changes

2023-10-20 20:35 UTC, turetske commented on docs/pages/client-usage.mdx
> +
Do we want direct references to ourselves? Specifically the 'justin.hiemstra' folder? Maybe make it more generic?

2023-10-24 15:06 UTC, jhiemstrawisc commented
One other quick comment -- it looks like each tab in the rendered index just reads the file name. Can you name the document something like `serving_an_origin.mdx`?

2023-10-24 15:18 UTC, joereuss12 approved these changes
LGTM

2023-10-24 16:07 UTC, turetske approved these changes
LGTM!

2023-10-24 16:07 UTC, merged