Renamed getOriginJWK to getServerJWK
PelicanPlatform/pelican pull request #339
Opened 2023-11-07 15:59 UTC by turetske

Close #314 

`getOriginJWK` is a confusing name because of the overloaded `origin` term. This changes that function to `getServerJWK`. If that's not an acceptable name, vscode makes refactoring very simple, so it can also be something like `getIssuerJWK` or `getHostJWK`.

2023-11-08 16:05 UTC, haoming29 requested changes
Just one small change hidden in the comment. LGTM otherwise.

2023-11-08 21:19 UTC, turetske commented
> When talking to @jhiemstrawisc on #359, I was thinking we should be more clear on different "private keys" used in the system, so I would suggest we use something like `GetIssuerPrivateJWK` to be extra clear on what this function is doing. @turetske Let me know your thoughts.

That sounds good to me and is a very quick fix.

2023-11-08 21:45 UTC, haoming29 commented
@turetske I think somehow you were on an older branch, the serveNamespaceRegister has been merged to main.

2023-11-08 21:54 UTC, turetske commented
@haoming29 Yeah. Something went weird with my rebase, thanks for catching it.

2023-11-09 15:38 UTC, turetske commented
@haoming29 Okay, those commit issues should be fixed now.

2023-11-09 15:45 UTC, haoming29 approved these changes
LGTM. Confirmed that no obvious legacy `getOriginJWK` left. Thanks for managing the conflicts.

2023-11-09 15:45 UTC, haoming29 commented on web_ui/authorization.go
Thanks for catching this!

2023-11-09 16:11 UTC, merged