Draft integration of namespace registry app in Pelican
PelicanPlatform/pelican pull request #39
Opened 2023-08-14 17:49 UTC by jhiemstrawisc

This is a draft for integrating Yuxiao's namespace server into the main pelican framework, with hookups to the CLI and the ability to serve the namespace registration app directly through the Pelican binary itself. There are a few important things to note about this as of the time of opening the draft PR:

1. I made a few choices about changing names of a few files that had "namespace" in the title, but we may choose to revert these changes. Personally, I think that calling the namespace server "namespace" is a bit confusing, mostly because we can register a namespace, but the thing we serve is not the namespace, but the registry itself. I tried to reflect this distinction by using the term registry.
2. When Yuxiao handed this over to me, he mentioned limitations regarding manipulation of namespace prefixes that had preceding or internal /'s. I started looking into how I could resolve these limitations, but it seems like there are limitations within gin's zero-allocation router itself that make this difficult. We could probably implement a custom regex middleware router, but that seems contrary to why we're using Gin. I was hoping to start a conversation about this before settling on a solution.
3. There's currently no security included with the command for deleting namespaces, and that's obviously not good. I was also hoping to discuss this before working on it

2023-08-16 16:09 UTC, bbockelm commented
For this item:

> When Yuxiao handed this over to me, he mentioned limitations regarding manipulation of namespace prefixes that had preceding or internal /'s

What do you mean by this?  It seems like we should always normalize the incoming data with something like the following:

```
input := "/foo//bar"
path.Clean("/" + input)
```

That way, we ensure that we only get absolute paths (`foo/bar` doesn't make sense here).

2023-08-16 17:57 UTC, jhiemstrawisc commented
The problem is in routing to handler functions. From what I can tell, Gin can take two different types of wild cards for setting up routing groups, and they are `/cli-namespaces/:prefix/suffix` and `/cli-namespaces/*wildcard`. In the first case, `prefix` will only be read up until the the first `/` after it starts, so there's no good way to route a request to `/cli-namespaces/my/namespace/issuer.jwks`  because it won't match `/cli-namespaces/:prefix/issuer.jwks`. For that path, we'd need the router to be `/cli-namespaces/:prefix1/:prefix2/issuer.jwks`.

Another headache with this is that currently when the client tries to delete the namespace `/my/namespace`, it sends a DELETE request for the resource `/cli-namespaces//my/namespace` and Gin cannot match that route by using the `:prefix` style wildcard because of the double slash. 

On the other hand, the `*wildcard` grabs everything after that point, so `/cli-namespaces/my/namespace` would match `/cli-namespaces/*wildcard`, but that prevents us from declaring any route after `/cli-namespaces/` because it will conflict with the wildcard. 

One solution might be to use some middleware that grabs everything after `/cli-namespaces` and determines the appropriate route, but then we lose some of the benefits from Gin.

2023-08-21 13:59 UTC, bbockelm requested changes
Lots of minor refactoring requested -- probably simply small cleanups from the rush to get it handed off when Yuxiao left.

2023-08-21 13:59 UTC, bbockelm commented on cmd/namespace_registry.go
> +/*
Remove the copyright statement for now.

IIUC, the copyright goes to Morgridge... to do this in bulk, I created a separate issue on the topic: https://github.com/PelicanPlatform/pelican/issues/42

2023-08-21 13:59 UTC, bbockelm commented on cmd/namespace_registry_serve.go
> +	// "github.com/pelicanplatform/pelican/config"
Remove commented-out lines

2023-08-21 13:59 UTC, bbockelm commented on cmd/namespace_registry_serve.go
> +		return fmt.Errorf("Unable to initialize the namespace registry database: %q", err)
Switch to `errors.Wrapf` to wrap the error instead of converting the underlying error to a string.

2023-08-21 13:59 UTC, bbockelm commented on cmd/namespace_registry_serve.go
> +		return fmt.Errorf("Failed to generate TLS certificate: %q", err)
Switch to `errors.Wrapf` to wrap the error instead of converting the underlying error to a string.

2023-08-21 13:59 UTC, bbockelm commented on config/config.go
> +		viper.SetDefault("OIDCClientIDFile", "/etc/pelican/ns-registry/client-id")
Can we avoid making a subdir here?  Maybe just a longer filename?

2023-08-21 13:59 UTC, bbockelm commented on config/config.go
> +		viper.SetDefault("GeoIPLocation", filepath.Join(configBase, "maxmind", "GeoLite2-City.mmdb"))
This is overwritten about 4 lines later.  Which is preferred?

2023-08-21 13:59 UTC, bbockelm commented on namespace-registry/client_commands.go
> +		return nil,err
Add space:
```suggestion
		return nil, err
```

2023-08-21 13:59 UTC, bbockelm commented on namespace-registry/client_commands.go
> +	respData := respToJSON(resp)
Switch to unmarshaling from a struct.  That way we can avoid some of the boilerplate type safety issues.

2023-08-21 13:59 UTC, bbockelm commented on namespace-registry/client_commands.go
> +			return fmt.Errorf("Failed to make request: %s\n", err)
Wrap error.

2023-08-21 13:59 UTC, bbockelm commented on namespace-registry/client_commands.go
> +			fmt.Printf("Waiting for approval. Press Enter after verification.\n")
If there's no formatting to be done, I think you want `fmt.Println` instead?

2023-08-21 13:59 UTC, bbockelm commented on namespace-registry/client_commands.go
> +		return fmt.Errorf("Failed to retrieve public key: %w\n", err)
Across this function, switch from formatting errors to wrapping them.

2023-08-21 13:59 UTC, bbockelm commented on namespace-registry/client_commands.go
> +	xBytes, _ := base64.RawURLEncoding.DecodeString(jwks["x"])
Handle errors here and the next line.

2023-08-21 13:59 UTC, bbockelm commented on namespace-registry/client_commands.go
> +	return body, nil
This function doesn't check the HTTP status code, meaning a `500`- or `403`-type response is going to be marked as successful.

2023-08-21 13:59 UTC, bbockelm commented on namespace-registry/registry.go
> +	_, cnOk := data["client_nonce"].(string)
This boilerplate could all be avoided with a struct-based deserialization.

2023-08-21 13:59 UTC, bbockelm commented on namespace-registry/registry.go
> +	x := jwks["x"].(string)
Add back in the error handling.

2023-08-21 13:59 UTC, bbockelm commented on namespace-registry/registry.go
> +func cliRegisterNamespace(c *gin.Context) {
Rename from `c` to `ctx`; using `c` makes it hard to search for the variable in text editors.

2023-08-21 13:59 UTC, bbockelm commented on namespace-registry/registry.go
> +			log.Errorln(err)
Missing an error return and response.

2023-08-21 13:59 UTC, bbockelm commented on namespace-registry/registry.go
> +		log.Errorln("An OIDC Client Identity file must be specified in the config (OIDCClientIDFile), or the identity must be provided via the environment variable PELICAN_OIDCCLIENTID")
Missing an error return and response.

2023-08-21 13:59 UTC, bbockelm commented on namespace-registry/registry.go
> +	router.POST("/cli-namespaces/registry", cliRegisterNamespace)
Let's dump the `cli-` prefix.  Affix this to the common API prefix used by other components.

2023-08-30 02:13 UTC, bbockelm approved these changes
Ok - still a few rough spots here but the major ones are all recorded as separate issues.  To avoid this PR from becoming any larger, I'm going to merge now.

2023-08-30 02:13 UTC, merged