Periodically prepare a combined custom + system CA bundle
PelicanPlatform/pelican pull request #406
Opened 2023-11-23 18:30 UTC by bbockelm

Both XRootD and Prometheus can't use our custom transport object, which combines the system CA pool with the custom CA.  This causes various failures unless you disable TLS validation (which we want to avoid doing).

This adds a helper function that periodically (re)creates the CA bundle. These bundles are made available to other functions at runtime.

NOTE: Neither Mac nor Windows have a standard system bundle.  On those platforms, we only create the bundle if the custom CA is present.

2023-11-27 15:45 UTC, bbockelm commented
@turetske - this is the PR I mentioned at standup.  It creates a "Pelican CA bundle" for use by components that can't utilize our custom transport inside the `pelican` process.

2023-11-29 19:07 UTC, turetske requested changes
Small spelling changes.

Just to make sure I understand what's occurring in the code: This is periodically taking our custom certs and the system certs, combining them into one file, and then writing that file out to a common location for prometheus and xrootd (in this case) to read?

2023-12-01 14:03 UTC, bbockelm commented on utils/ca_utils.go
> +// isSameDirSymlink reports whether fi in dir is a symlink with a
Done!

2023-12-01 14:03 UTC, bbockelm commented on utils/ca_utils.go
> +// for components that do not use go's trusted CA stroe
Done!

2023-12-01 22:25 UTC, bbockelm commented
Overriding branch  protections since I addressed @turetske's comments (and want to build on top of this in order to make the cache easier to test).  The test failure appears to be spurious and fixed elsewhere.

2023-12-01 22:25 UTC, merged