Placeholder namespace UI 354
PelicanPlatform/pelican pull request #478
Opened 2023-12-08 17:39 UTC by CannonLock

2023-12-08 19:00 UTC, haoming29 requested changes

2023-12-08 19:00 UTC, haoming29 commented on web_ui/frontend/components/NamespaceTable.tsx
> +    const keyToName = {
Can we add `identity` to the table as well? I think we'd like to have it for admin to do approval work as the next step

2023-12-08 19:36 UTC, haoming29 approved these changes
LGTM for the UI part. @jhiemstrawisc when you have time, could you peek at the Go code and see if I missed anything for this PR?

2023-12-11 19:22 UTC, turetske approved these changes
Seems good to me

2023-12-11 19:22 UTC, merged