Have cache and origin run on Cache.Port and Origin.Port, respectively
PelicanPlatform/pelican pull request #590
Opened 2024-01-03 16:18 UTC by bbockelm

This deprecates the Xrootd.Port configuration and replaces it with Origin.Port and Cache.Port.  By separating out the configs, we have some hope of making the cache module part of the "federation in a box" since the cache will need to be a standalone Xrootd instance.

With this, Server.WebPort and Cache.Port/Origin.Port (as appropriate) are a hard requirement for the various modules to be enabled, requiring some unit tests to set these values.

Additionally, XRootD can be told to bind to "any" available TCP port.  If one of the port values is set to 0, then convert it to `any` in the xrootd configuration.  This mode is not yet useful because we need to feed back the selected port into the pelican configuration (and the only way to get the selected port is to scrape through the xrootd logs) -- however, it'll be invaluable for running multiple unit tests in parallel in the future.

2024-02-07 14:33 UTC, bbockelm commented
Update on the PR (for @jhiemstrawisc who I added as reviewer):
- This now adds a simple logging filter to allow us to trigger a callback on the contents of logs
- With the filter, we can look for xrootd's log line indicating the port it starts up on.
- Splits out the launching of the listener from the web UI.  Allows us to start the listener first, get the random port it selected, and then update our internal configuration to match.
- Adds type safety across the `token_scope.TokenScope` usage.
- Migrates all origin issuer URLs to the web UI instead of XRootD.
- Changes a handful of tests to bind to random ports instead of fixed ones.

2024-02-13 14:59 UTC, jhiemstrawisc requested changes
A few small questions and minor requests for comments, otherwise LGTM.

2024-02-13 17:06 UTC, turetske commented
This will cause issues with the broker_client.go changes you made. https://github.com/PelicanPlatform/pelican/blob/ebff302dbd1132a0e16b7b2470986787e58a4acb/origin_ui/broker_client.go#L65C1-L66C1 Uses Xrootd.Port. I suggest doing a grep for "Xrootd_Port" and "Xrootd.Port" after a rebase in order to make sure any deprecated uses are removed.

2024-02-13 17:07 UTC, turetske requested changes
This will cause issues with the broker_client.go changes you made. https://github.com/PelicanPlatform/pelican/blob/ebff302dbd1132a0e16b7b2470986787e58a4acb/origin_ui/broker_client.go#L65C1-L66C1 Uses Xrootd.Port. I suggest doing a grep for "Xrootd_Port" and "Xrootd.Port" after a rebase in order to make sure any deprecated uses are changed appropriately.

2024-02-16 14:22 UTC, bbockelm commented on docs/parameters.yaml
> +  The TCP port to be used by the origin service for serving files
Done!

2024-02-16 14:22 UTC, bbockelm commented on config/logging.go
> +func (fh *RegexpFilterHook) Fire(entry *log.Entry) (err error) {
Done!

2024-02-16 14:50 UTC, jhiemstrawisc approved these changes
LGTM

2024-02-16 15:08 UTC, turetske approved these changes
LGTM!

2024-02-16 19:47 UTC, merged