Add user role to `/auth/whoami` response
PelicanPlatform/pelican pull request #619
Opened 2024-01-08 22:04 UTC by haoming29

Add user role ("admin" for user with admin privilege or "user" if they don't) so that UI can do RBAC.

2024-01-08 22:06 UTC, haoming29 commented
@CannonLock This PR should give you what you need

2024-01-09 17:34 UTC, joereuss12 requested changes
LGTM other than this one simple change

2024-01-09 17:34 UTC, joereuss12 commented on web_ui/authentication.go
> +func whoamiHandler(ctx *gin.Context) {
Maybe add comments before this function as well, just to remain consistent even though it is pretty self-explanitory

2024-01-09 18:42 UTC, joereuss12 approved these changes
LGTM

2024-01-09 18:42 UTC, merged