Filter config
PelicanPlatform/pelican pull request #669
Opened 2024-01-17 21:33 UTC by CannonLock

Closes https://github.com/PelicanPlatform/pelican/issues/654

2024-01-30 21:18 UTC, CannonLock commented
@haoming29 Alright this is ready for review, copying the parameters.json was more of a adventure then it needed to be.

2024-01-30 23:00 UTC, haoming29 requested changes
LGTM. One thing I noticed is that after I ran `make web-build`, there's a new file generated at `frontend/public/data/parameters.json` which is not added to `.gitignore`. Is this file supposed to be committed? If so, could you add it to your PR? Or it's a file for local only?

2024-01-30 23:00 UTC, haoming29 commented on generate/param_generator.go
> +	// Create the json file to be generated (for the documentation website
```suggestion
	// Create the json file to be generated (for the documentation website)
```

2024-01-31 22:29 UTC, haoming29 approved these changes
LGTM with changes

2024-01-31 22:39 UTC, merged