Enable OSDF defaults for stashcp/stash_plugin as well
PelicanPlatform/pelican pull request #721
Opened 2024-01-30 19:31 UTC by bbockelm

NOTE: This switches the default for the plugin to use the director which will migrate a large amount of load to the director compared to what's currently seen.

Fixes #720

2024-02-01 22:10 UTC, joereuss12 commented
@bbockelm After lots of digging, reading through code, poking Justin for opinions a ton, and trial and errors this is the solution I came up with. Now we should recognize the hostname in pelican:// url's and discover the federation correctly. The problem was when using an `osdf` or `stash` binary with a pelican url, we always used the osdf defaults (even when the hostname is specified to `pelican.example.com`). This should properly unset federation urls and rediscover the federation with the specified hostname in the object url.

2024-02-02 16:15 UTC, joereuss12 commented
Found some lines that you forgot to delete, otherwise this PR looks good to me. I think I'll have someone else look at this though for some double checking to make sure neither of us missed anything. However, all my tests seem to be passing.

2024-02-02 18:49 UTC, jhiemstrawisc requested changes
One small cleanup, otherwise LGTM

2024-02-02 18:49 UTC, jhiemstrawisc commented on client/main.go
>  // FIXME: GetCacheHostnames is not director-aware!
I think this change makes this FIXME false. Let's get rid of it.

2024-02-03 03:30 UTC, bbockelm commented
Since it's now been reviewed by @joereuss12 and @jhiemstrawisc -- and I see that @joereuss12 has addressed the last request -- I'm going to use my admin powers to clear up the state and merge the PR.

2024-02-03 03:31 UTC, merged