Fixes to xrootd logging config
PelicanPlatform/pelican pull request #776
Opened 2024-02-06 20:55 UTC by joereuss12

Changes include:
- Xrootd logging now uses the standard logrus logging values
- Instead of string comparisons for mapping, we now use log.ParseLevel and compare the levels (which are unsigned ints)
- The program now exits when there is an improper config value and returns a proper error
- Anywhere these configs are listed, they are all listed alphabetically for consistency and an easier time finding each option
- Unit tests for the generation of the xrootd config file

2024-02-06 20:55 UTC, joereuss12 commented
Let me know if I missed anything or need to add anything else! Hopefully this patches everything up.

2024-02-11 00:23 UTC, bbockelm requested changes
Two things:
- See comments for one potential way to rewrite the `mapXrootdLogLevels` to be a bit more readable.
- Talk with @matyasselmeci about the description of the configuration parameters.  I feel they're still not particularly approachable.  How to write them to make sense to someone with little knowledge about XRootD?

2024-02-11 00:23 UTC, bbockelm commented on xrootd/xrootd_config.go
> +		xrdConfig.Logging.OriginCms = "-all"
Use `fallthrough` for duplicate lines.

Doesn't save lines of code -- but does show intent (that things are supposed to be duplicated).

2024-02-11 00:23 UTC, bbockelm commented on xrootd/xrootd_config.go
> +		xrdConfig.Logging.OriginCms = "-all"
Actually, better yet, let's wrap this all into a function.  Here's an idea:

- Create a struct called `loggingMap` or similar.  Have each of the logging levels be a separate member of the struct.
- Iterate from top to bottom of the struct (in order of the logging levels).  If the string is set, use that in the xrdConfig.  If it's not set, use the prior value.
- Have a single helper function `genLoggingConfig` that does all the translation, including error messages.

`loggingMap` might look like:

```
type loggingMap struct {
    Trace string
    Debug string
    ...
    Panic string
}
```

So, in this case, we might see:

```
xrdConfig.Logging.OriginCms, err = genLoggingConfig(
    param.Logging_Origin_Cms.GetString(),
    loggingMap {
        Trace: "debug",
        Info: "all",
        Error: "-all",
    }
)
if err != nil {
    ...
}
```

That's about as compact as I can think of making this.

2024-02-20 16:23 UTC, joereuss12 commented
Note: still need to make the config params more approachable and user-friendly, but thought I'd push my work in progress

2024-02-29 21:21 UTC, bbockelm requested changes
Very close.

I like the new, much more compact, style of setting the log levels.  It makes the code quite readable.

Only thing I spotted were some logging categories don't really make sense (e.g., setting logging for cache-related modules in the origin config).

2024-03-05 15:49 UTC, haoming29 requested changes
One small question and we should be good to go

2024-03-05 15:49 UTC, haoming29 commented on xrootd/ca-bundle.crt
Are we intended to include these CAs in git? and why there's a CA update in log config PR?

2024-03-05 15:52 UTC, joereuss12 commented on xrootd/ca-bundle.crt
Oh, not sure how I missed these getting added. I'm assuming they should not be there. I can try to remove them

2024-03-05 16:25 UTC, joereuss12 commented
Okay @haoming29 cleanup has happened. Just waiting for tests to pass to make sure I didn't remove anything important but I think everything should be good to go!

2024-03-05 19:39 UTC, haoming29 approved these changes
LGTM with the extra files removed. Thanks for taking care of this!

2024-03-05 19:40 UTC, haoming29 commented
@joereuss12 You might need to ask @jhiemstrawisc to overwrite Brian's requested change to get this merged in

2024-03-05 20:19 UTC, jhiemstrawisc commented
@Haoming, since you've been reviewing for Brian, can you resolve any of the the conversations that are open that have a fix? Once I see everything resolved, I'll merge

2024-03-05 20:23 UTC, haoming29 commented
> @haoming, since you've been reviewing for Brian, can you resolve any of the the conversations that are open that have a fix? Once I see everything resolved, I'll merge

@jhiemstrawisc  Peek through the conversations and looks to me they have all been taken care of. Resolved conversations accordingly

2024-03-05 20:25 UTC, jhiemstrawisc commented
Perfect, thanks. Just wanted the acknowledgement from someone for bookkeeping since I'm not reviewing myself :) Consider it merged! Thanks to everyone who worked on this

2024-03-05 20:25 UTC, merged