Reorganize project to have less intertwined internal dependency
PelicanPlatform/pelican pull request #844
Opened 2024-02-22 19:36 UTC by haoming29

This PR originally was to work on #559, but quickly I realized that we still have many instances in the codebase where dependency is messed up and put us at the fringe of cyclic import. So this PR took a digression to focus on cleaning up unnecessary import of server packages to other internal packages, as well as pulling commonly used code to correct places.

2024-02-29 19:30 UTC, bbockelm commented
@haoming29 - can you clear up the merge conflicts?

2024-03-01 16:06 UTC, haoming29 commented
> @haoming29 - can you clear up the merge conflicts?

Done

2024-03-04 15:50 UTC, jhiemstrawisc requested changes
One small change request, otherwise looks good to me. At some point soon, I think the team should have a quick sync up to talk about all the utility functions we have so that we can settle on best practices. Things are moving around frequently enough that it's getting hard to keep track of whether particular functions already exist.

2024-03-04 15:50 UTC, jhiemstrawisc commented on registry/client_commands.go
> +	issuerURL, err := server_utils.GetNSIssuerURL(prefix)
It looks like you can remove the previous TODO. I think this function has drifted both in name and location.

2024-03-05 16:48 UTC, jhiemstrawisc approved these changes
LGTM. Thanks Haoming!

2024-03-05 16:48 UTC, merged