Added error when discovery-url contains a path
PelicanPlatform/pelican pull request #860
Opened 2024-02-28 17:10 UTC by joereuss12

When a discovery-url contains a path (when set in config or with `-f`), we will throw an error when we call DiscoverFederation on that url. If it is contained within a `pelican://` url however, we cannot really catch that specific error since we will assume any paths added to the discovery-url to be the namespace-prefix and so on. Therefore, I added a few notes to the documentation alerting that this will fail.

Note: I realize the client-usage docs are out of date but I added this for when we refresh the docs

2024-02-29 01:00 UTC, bbockelm requested changes
Please add a test for setting the federation URL to `osg-htc.org` (or similar -- just the hostname but not specifying the scheme).

Go parses this form as a path with no hostname and, I suspect, this change breaks that case (which is the default for OSDF).

2024-03-04 15:19 UTC, joereuss12 commented
@bbockelm I think I need the okay for this one since you requested changes.

2024-03-04 16:04 UTC, jhiemstrawisc requested changes
Just a few small things.

2024-03-04 16:04 UTC, jhiemstrawisc commented on config/config_test.go
> +		assert.Error(t, err)
It's nice to have our tests not only assert that there _is_ an error, but that the correct error is returned. It's also nice to look at these types of tests as an index of "if I do XXX I get an error that says YYY". Can modify this to use something like `assert.ErrorIs(t TestingT, err, target error, msgAndArgs ...interface{})`?

2024-03-06 14:22 UTC, jhiemstrawisc approved these changes
LGTM. Thanks Joe!

2024-03-06 14:23 UTC, jhiemstrawisc commented
Bypassing branch protections to avoid waiting for the extra review since I took point on this one.

2024-03-06 14:24 UTC, merged