Split container images by server type and replace supervisord by tini
PelicanPlatform/pelican pull request #883
Opened 2024-03-01 21:49 UTC by haoming29

Closes #526 

A couple of other changes:
* Only run OA4MP setup script for origin container
* Added .dockerignore to ignore static files and `node_moduels`
* Only log into harbor when it's in pelican main repo, as thing for push container
* Merge `release-container.yml` with `publish-container.yml` to reuse most of the logic
* Cached container image build to GHA cache

2024-03-01 22:27 UTC, jhiemstrawisc commented
If we want to make containers as lightweight as possible, the S3 plugin only needs to be added to origin images. Lotman will only need to be in cache containers.

2024-03-01 22:30 UTC, haoming29 commented
> If we want to make containers as lightweight as possible, the S3 plugin only needs to be added to origin images. Lotman will only need to be in cache containers.

@jhiemstrawisc  Agree. There's a ton of dependencies only for origin/cache. Director and registry can mostly run out of the pelican binary without any dependency. I'd like to clean that up which can also speed up the building speed for director and registry image, but Brian suggests to hold on doing that, rather, get the idea work first. So I guess the dependency split will be a separate ticket

2024-03-04 17:19 UTC, matyasselmeci requested changes
Two suggestions related to tini; otherwise, it looks fine, though @brianhlin may want to check the GHA changes.

2024-03-04 17:19 UTC, matyasselmeci commented on images/Dockerfile
> +    mv tini /bin/tini
tini is available in the EPEL repos; you should install it via yum (probably in the 'dependency-build' stage that this stage inherits from).

2024-03-04 17:19 UTC, matyasselmeci commented on images/entrypoint.sh
> +            /pelican/pelican "$@"
```suggestion
            exec tini /pelican/pelican "$@"
            # we shouldn't get here
            echo >&2 "Exec of tini failed!"
            exit 1
```

2024-03-04 17:19 UTC, matyasselmeci commented on images/entrypoint.sh
> +            /pelican/osdf "$@"
```suggestion
            exec tini /pelican/osdf "$@"
            # we shouldn't get here
            echo >&2 "Exec of tini failed!"
            exit 1
```

2024-03-04 18:12 UTC, matyasselmeci approved these changes

2024-03-04 18:14 UTC, matyasselmeci commented
LGTM. Thanks!

2024-03-06 16:02 UTC, brianhlin approved these changes
A small suggestion and a few requests for comments but otherwise LGTM

2024-03-06 16:09 UTC, haoming29 commented on .github/workflows/build-prod-container.yml
> +        default: true
This is called by `pre-release.yaml` that handles the release process

2024-03-06 16:09 UTC, haoming29 commented on .github/workflows/build-prod-container.yml
> +          echo "branch=${GITHUB_REF_NAME%.*}.x" >> $GITHUB_OUTPUT
This is not part of my change but @CannonLock should be able to answer this question

2024-03-06 16:25 UTC, brianhlin commented on .github/workflows/build-prod-container.yml
> +        default: true
Ah, there's something wrong with my git repo search. I see it now, thanks!

2024-03-06 16:27 UTC, haoming29 commented on .github/workflows/build-prod-container.yml
> +        default: true
Probably because of the renaming of GHA files

2024-03-06 16:33 UTC, merged

2024-03-06 17:40 UTC, brianhlin commented on .github/workflows/build-prod-container.yml
> +        default: true
Nope! I just found some bitrot in my editor config and it's not searching through hidden files.

2024-03-06 17:57 UTC, matyasselmeci commented
Thanks! Looking forward to trying it out.