Unit test for statHttp within Pelican Client
PelicanPlatform/pelican pull request #890
Opened 2024-03-05 15:26 UTC by joereuss12

Added unit test for statHttp within Pelican client. Note: this should not be merged until #884 is completed since currently statHttp only works with topology.

2024-03-18 21:38 UTC, joereuss12 commented
Note: the osdf:// stat test is currently a pelican url. This is waiting for #878 to be merged before fixing. Made issue #961 to do this

2024-03-25 16:23 UTC, haoming29 requested changes
LGTM with one small change requested

2024-03-25 16:23 UTC, haoming29 commented on client/fed_test.go
> +		defer os.Remove(tempFile.Name())
I saw that `NewFedTest` removes all files at the end of the test, so this is not needed.

2024-03-25 16:23 UTC, haoming29 commented on client/fed_test.go
> +		defer os.Remove(tempFile.Name())
same here

2024-03-25 16:23 UTC, haoming29 commented on client/fed_test.go
> +		defer os.Remove(tempFile.Name())
here

2024-03-28 21:58 UTC, haoming29 approved these changes
LGTM!

2024-03-28 21:58 UTC, merged