Cache can now filter to only serve a list of provided namespaces
PelicanPlatform/pelican pull request #893
Opened 2024-03-05 20:37 UTC by turetske

-- Will default to all namespaces if not set
	-- Filtering is done at the cache side

closes #312

2024-03-06 16:13 UTC, jhiemstrawisc requested changes

2024-03-06 16:13 UTC, jhiemstrawisc commented on docs/parameters.yaml
> +  A list of namespaces the cache is allowed to pull from. If the list is empty, it's assumed that
I'd also say "If the list is empty or this option is unset".

2024-03-06 16:13 UTC, jhiemstrawisc commented on docs/parameters.yaml
> +name: Cache.AcceptedNamespaces
How about `Cache.PermittedNamespaces`?

2024-03-06 16:13 UTC, jhiemstrawisc commented on cache_ui/advertise.go
> +	if viper.IsSet("Cache.AcceptedNamespaces") {
If I set this with an empty list flow:
```
Cache:
  AcceptedNamespaces: []
```

What happens?

2024-03-06 16:40 UTC, turetske commented on cache_ui/advertise.go
> +				splitIndex := strings.LastIndex(ns, "/")
Good point. I'll put in something to check for both.

2024-03-06 16:41 UTC, turetske commented on cache_ui/advertise_test.go
> +			Path: "ns1",
Good point, will do.

2024-03-08 19:44 UTC, jhiemstrawisc requested changes
Just a few small things, otherwise I think this is looking good.

2024-03-08 19:44 UTC, jhiemstrawisc commented on cache_ui/advertise.go
> +		if ns[0] != '/' {
Maybe use `strings.HasPrefix`? If someone provides a bad configuration, ns might be empty. I think `strings.HasPrefix` handles being passed an empty string.

2024-03-08 19:44 UTC, jhiemstrawisc commented on cache_ui/advertise.go
> +	* Filters out ads based on the namespaces listed in server.NamespaceFiler
Typo in `server.NamespaceFiler`

2024-03-08 19:44 UTC, jhiemstrawisc commented on cache_ui/advertise.go
> +			if ns[len(ns)-1] != '/' {
Maybe `strings.HasSuffix`?

2024-03-11 14:14 UTC, jhiemstrawisc approved these changes
LGTM. Thanks!

2024-03-11 14:14 UTC, merged