Enabling OAuth for the origin, adding support for Globus as another auth server
PelicanPlatform/pelican pull request #963
Opened 2024-03-19 20:50 UTC by haoming29

Closes #928

2024-04-02 21:49 UTC, haoming29 commented
@bbockelm any chance that I could get a review in soon? since this is a critical item for 7.7 release and Cannon's login UI change also depends on this PR to be merged, or do you want to hand this off to someone else?

2024-04-05 02:12 UTC, bbockelm requested changes
Very minor changes requested.  Some of the formatting nitpicks I fixed up already in a pushed commit.

2024-04-05 15:30 UTC, haoming29 commented on oauth2/oidc_client.go
> +	CILogon         OIDCProvider = "CILogon"
Issue created: https://github.com/PelicanPlatform/pelican/issues/1054

2024-04-05 16:35 UTC, haoming29 commented
@CannonLock as I was going over the code to address the code review comments, I realized that I didn't use `Origin.EnableOIDC` flag that we meant to use for conditionally turn on the OAuth for origin (and cache), so we need to update the UI as well to conditionally render the OAuth options based on the server config. To make your life easier, I have an API included in this PR at `/api/v1.0/auth/oauth`, a `GET` request will give you an object with key `oidc_enabled_servers` which is a list of servers that enable OAuth (also documented in the Swagger). You should be able to iterate over the enabledServers list and match the `oidc_enabled_servers` to see which server turns on the option. Let me know if that makes sense

2024-04-08 15:18 UTC, haoming29 commented
Hey @bbockelm, could you take another look at this PR? This one is blocking the release

2024-04-09 02:37 UTC, bbockelm approved these changes
Revisions LGTM.

2024-04-09 14:22 UTC, merged